name: Reload Shiny App

on:
  push:
    paths:
      - 'question_bank.json'

jobs:
  reload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Reload Shiny App
        env:
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
        run: |
          # Replace <app-url> with the URL of your Shiny app
          # Include the Shiny token in the request headers
          curl -X POST -H "Authorization: Bearer $SHINY_TOKEN" "https://tsu2000.shinyapps.io/exbook/__reload__/"
